-- CREATE DATABASE IF NOT EXISTS STOCKS_FEED;
CREATE TABLE IF NOT EXISTS USERS(
    id SERIAL,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    API_KEY VARCHAR(255)
);
